<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-15T20:17:15 IST" name="Suite" finished-at="2022-07-15T20:17:26 IST" duration-ms="10756">
    <groups>
    </groups>
    <test started-at="2022-07-15T20:17:15 IST" name="Test" finished-at="2022-07-15T20:17:26 IST" duration-ms="10756">
      <class name="TestRunner.TestRunner">
        <test-method signature="runTest()[pri:0, instance:TestRunner.TestRunner@55b7a4e0]" started-at="2022-07-15T20:17:16 IST" name="runTest" finished-at="2022-07-15T20:17:26 IST" duration-ms="10658" status="FAIL">
          <exception class="org.opentest4j.AssertionFailedError">
            <message>
              <![CDATA[status code was: 404, expected: 200, response time in milliseconds: 866, url: https://gorest.co.in/public/v2/posts/100, response: 
{"message":"Resource not found"}
classpath:Features/getmethodExample.feature:8
status code was: 404, expected: 200, response time in milliseconds: 1100, url: https://gorest.co.in/public/v1/users/30, response: 
{"meta":null,"data":{"message":"Resource not found"}}
classpath:Features/token.feature:10 ==> expected: <0> but was: <2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.opentest4j.AssertionFailedError: status code was: 404, expected: 200, response time in milliseconds: 866, url: https://gorest.co.in/public/v2/posts/100, response: 
{"message":"Resource not found"}
classpath:Features/getmethodExample.feature:8
status code was: 404, expected: 200, response time in milliseconds: 1100, url: https://gorest.co.in/public/v1/users/30, response: 
{"meta":null,"data":{"message":"Resource not found"}}
classpath:Features/token.feature:10 ==> expected: <0> but was: <2>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:542)
at TestRunner.TestRunner.testParallel(TestRunner.java:30)
at TestRunner.TestRunner.runTest(TestRunner.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.opentest4j.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTest -->
      </class> <!-- TestRunner.TestRunner -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
